# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "prod-gles_common"
BBFILE_PATTERN_prod-gles_common = "^${LAYERDIR}/"
BBFILE_PRIORITY_prod-gles_common = "12"

LAYERSERIES_COMPAT_prod-gles_common = "kirkstone"
