# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-fastboot-poc"
BBFILE_PATTERN_meta-fastboot-poc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-fastboot-poc = "6"

LAYERDEPENDS_meta-fastboot-poc = "core"
LAYERSERIES_COMPAT_meta-fastboot-poc = "dunfell kirkstone"

IMAGE_INSTALL:append = " \
    drm-color-bar \
"

KERNEL_DEVICETREE:append = " \
    renesas/r8a779g0-whitehawk_cr52_rproc.dtb \
"

